package dev.zacsweers.metro.compiler.reports

import org.jetbrains.kotlin.fir.declarations.*
import org.jetbrains.kotlin.name.ClassId

/**
 * Report capturing FIR (Frontend Intermediate Representation) generation details.
 * Documents the declarations and structures created during the FIR phase.
 */
internal data class FirGenerationReport(
  val graphName: String,
  val classId: ClassId,
  val declarations: List<FirDeclarationInfo>,
  val nestedClasses: List<NestedClassInfo>,
  val generationTimeMs: Long,
) {

  /**
   * Information about a FIR declaration (property, function, constructor, etc.)
   */
  data class FirDeclarationInfo(
    val name: String,
    val type: DeclarationType,
    val visibility: String,
    val modality: String,
    val additionalInfo: Map<String, String> = emptyMap(),
  )

  /**
   * Information about nested classes generated
   */
  data class NestedClassInfo(
    val name: String,
    val type: String, // "class", "object", "interface"
    val purpose: String, // e.g., "SwitchingProvider", "Shard1", etc.
    val declarationCount: Int,
  )

  enum class DeclarationType {
    CONSTRUCTOR,
    PROPERTY,
    FUNCTION,
    NESTED_CLASS,
    COMPANION_OBJECT,
  }

  /**
   * Generates a Markdown report of FIR generation.
   */
  fun toMarkdown(): String = buildString {
    appendLine("# FIR Generation Report")
    appendLine()
    appendLine("## Graph Information")
    appendLine("- **Graph Name**: `$graphName`")
    appendLine("- **Class ID**: `$classId`")
    appendLine("- **Generation Time**: ${generationTimeMs}ms")
    appendLine()

    if (nestedClasses.isNotEmpty()) {
      appendLine("## Nested Classes")
      appendLine("| Name | Type | Purpose | Declarations |")
      appendLine("|------|------|---------|--------------|")
      nestedClasses.forEach { nested ->
        appendLine("| ${nested.name} | ${nested.type} | ${nested.purpose} | ${nested.declarationCount} |")
      }
      appendLine()
    }

    appendLine("## Generated Declarations")

    val byType = declarations.groupBy { it.type }

    byType[DeclarationType.CONSTRUCTOR]?.let { constructors ->
      appendLine()
      appendLine("### Constructors (${constructors.size})")
      constructors.forEach { decl ->
        appendLine("- `${decl.visibility} ${decl.name}`")
        decl.additionalInfo.forEach { (key, value) ->
          appendLine("  - $key: $value")
        }
      }
    }

    byType[DeclarationType.PROPERTY]?.let { properties ->
      appendLine()
      appendLine("### Properties (${properties.size})")
      appendLine("| Name | Visibility | Modality | Info |")
      appendLine("|------|------------|----------|------|")
      properties.forEach { prop ->
        val info = prop.additionalInfo.entries.joinToString(", ") { "${it.key}: ${it.value}" }
        appendLine("| ${prop.name} | ${prop.visibility} | ${prop.modality} | $info |")
      }
    }

    byType[DeclarationType.FUNCTION]?.let { functions ->
      appendLine()
      appendLine("### Functions (${functions.size})")
      appendLine("| Name | Visibility | Modality | Info |")
      appendLine("|------|------------|----------|------|")
      functions.forEach { func ->
        val info = func.additionalInfo.entries.joinToString(", ") { "${it.key}: ${it.value}" }
        appendLine("| ${func.name} | ${func.visibility} | ${func.modality} | $info |")
      }
    }

    appendLine()
    appendLine("## FIR Code Structure")
    appendLine()
    appendLine("```kotlin")
    appendLine(generatePseudoCode())
    appendLine("```")

    appendLine()
    appendLine("---")
    appendLine("*Generated by Metro Compiler Plugin - FIR Phase*")
  }

  /**
   * Generates pseudo-code representation of the FIR structure
   */
  private fun generatePseudoCode(): String = buildString {
    appendLine("// FIR Generated Structure for $graphName")
    appendLine("class ${classId.shortClassName} {")

    // Constructors
    declarations.filter { it.type == DeclarationType.CONSTRUCTOR }.forEach { ctor ->
      val params = ctor.additionalInfo["parameters"] ?: ""
      appendLine("  ${ctor.visibility} constructor($params)")
    }

    appendLine()

    // Properties
    declarations.filter { it.type == DeclarationType.PROPERTY }.forEach { prop ->
      val type = prop.additionalInfo["type"] ?: "Any"
      val getter = if (prop.additionalInfo["hasGetter"] == "true") " get()" else ""
      appendLine("  ${prop.visibility} ${prop.modality} val ${prop.name}: $type$getter")
    }

    appendLine()

    // Functions
    declarations.filter { it.type == DeclarationType.FUNCTION }.forEach { func ->
      val params = func.additionalInfo["parameters"] ?: ""
      val returnType = func.additionalInfo["returnType"] ?: "Unit"
      appendLine("  ${func.visibility} ${func.modality} fun ${func.name}($params): $returnType")
    }

    // Nested classes
    if (nestedClasses.isNotEmpty()) {
      appendLine()
      nestedClasses.forEach { nested ->
        appendLine("  ${nested.type} ${nested.name} { /* ${nested.declarationCount} declarations */ }")
      }
    }

    appendLine("}")
  }

  /**
   * Generates a JSON report.
   */
  fun toJson(): String = buildString {
    appendLine("{")
    appendLine("  \"graphName\": \"$graphName\",")
    appendLine("  \"classId\": \"$classId\",")
    appendLine("  \"generationTimeMs\": $generationTimeMs,")
    appendLine("  \"declarationCount\": ${declarations.size},")
    appendLine("  \"nestedClassCount\": ${nestedClasses.size},")
    appendLine("  \"declarations\": [")
    declarations.forEachIndexed { index, decl ->
      appendLine("    {")
      appendLine("      \"name\": \"${decl.name}\",")
      appendLine("      \"type\": \"${decl.type}\",")
      appendLine("      \"visibility\": \"${decl.visibility}\",")
      appendLine("      \"modality\": \"${decl.modality}\"")
      append("    }")
      if (index < declarations.size - 1) append(",")
      appendLine()
    }
    appendLine("  ],")
    appendLine("  \"nestedClasses\": [")
    nestedClasses.forEachIndexed { index, nested ->
      appendLine("    {")
      appendLine("      \"name\": \"${nested.name}\",")
      appendLine("      \"type\": \"${nested.type}\",")
      appendLine("      \"purpose\": \"${nested.purpose}\",")
      appendLine("      \"declarationCount\": ${nested.declarationCount}")
      append("    }")
      if (index < nestedClasses.size - 1) append(",")
      appendLine()
    }
    appendLine("  ]")
    appendLine("}")
  }
}